apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scoutx-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: scoutx
      app.kubernetes.io/component: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: UDP
          port: 53
