apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scoutx-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scoutx
      app.kubernetes.io/component: web
