-- AlterTable
ALTER TABLE "user_profiles" 
ADD COLUMN IF NOT EXISTS "livingCountry" TEXT DEFAULT 'Vietnam',
ADD COLUMN IF NOT EXISTS "livingCountryCode" TEXT DEFAULT 'VN',
ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION DEFAULT 10.7769,
ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION DEFAULT 106.7009,
ADD COLUMN IF NOT EXISTS "availableForMissions" BOOLEAN NOT NULL DEFAULT true;
