apiVersion: v1
kind: Secret
metadata:
  name: scoutx-runtime
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@db:5432/scoutx?schema=public"
  JWT_SECRET: "super-long-secret-key-123456"
