apiVersion: v1
kind: Service
metadata:
  name: scoutx-web
  labels:
    app.kubernetes.io/name: scoutx
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: scoutx
    app.kubernetes.io/component: web
