-- AlterTable missions
ALTER TABLE "missions" 
ADD COLUMN IF NOT EXISTS "targetCities" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "targetGender" TEXT DEFAULT 'ANY',
ADD COLUMN IF NOT EXISTS "targetAgeRange" TEXT DEFAULT 'ANY',
ADD COLUMN IF NOT EXISTS "targetExperienceLevel" TEXT DEFAULT 'ANY',
ADD COLUMN IF NOT EXISTS "targetLanguages" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable user_profiles
ALTER TABLE "user_profiles" 
ADD COLUMN IF NOT EXISTS "gender" TEXT DEFAULT 'ANY',
ADD COLUMN IF NOT EXISTS "birthYear" INTEGER,
ADD COLUMN IF NOT EXISTS "languages" TEXT[] DEFAULT ARRAY['English', 'Vietnamese']::TEXT[],
ADD COLUMN IF NOT EXISTS "experienceLevel" TEXT DEFAULT 'INTERMEDIATE',
ADD COLUMN IF NOT EXISTS "availabilityType" TEXT DEFAULT 'FLEXIBLE',
ADD COLUMN IF NOT EXISTS "education" TEXT,
ADD COLUMN IF NOT EXISTS "certifications" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "yearsOfExperience" INTEGER DEFAULT 1;
