apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoutx-web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: staging.scoutx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scoutx-web
                port:
                  number: 80
