/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Copilot → Live Mission Orchestrator — P6
 *
 * Reads an APPROVED ResearchBrief + its ResearchPlan, then atomically:
 *  1. Creates the Mission (SURVEY type, status DRAFT)
 *  2. Attaches audience criteria (trust targeting fields)
 *  3. Attaches screening (screeningEnabled + screeningQuestions)
 *  4. Attaches quotas
 *  5. Creates SurveyQuestion rows from plan.survey.questions
 *  6. Reserves/escrows budget via CoinLedger (MISSION_REWARD_LOCK)
 *  7. Sets mission status → OPEN (published/live)
 *  8. Updates ResearchBrief → PUBLISHED
 *
 * AI DOES NOT CALL THIS. Only authenticated Requester/Admin can trigger it.
 * Escrow is atomic — if any step fails the entire tx rolls back.
 */
import { prisma } from "@/lib/prisma";
import { recordCoinMovement } from "@/lib/coin-ledger-service";
import { estimateAudienceSize } from "@/lib/audience-panel-service";

const GLOBAL_LOCATION_ID = "00000000-0000-0000-0000-000000000001";
const PLATFORM_FEE_RATE = 0.1; // 10%

export type PublishResult = {
  missionId: string;
  briefId: string;
  status: "PUBLISHED";
  escrowedCents: number;
  platformFeeCents: number;
  surveyQuestionsCreated: number;
  eligibleCount: number;
};

export async function publishCopilotBriefAsLiveMission(
  briefId: string,
  requesterId: string,
): Promise<PublishResult> {
  // ── 1. Load & validate brief
  const brief = await prisma.researchBrief.findUnique({
    where: { id: briefId },
    include: { plan: true },
  });

  if (!brief || brief.requesterId !== requesterId) {
    throw new Error("Brief not found or forbidden");
  }
  if (brief.status !== "APPROVED") {
    throw new Error(`Brief must be APPROVED before publishing. Current: ${brief.status}`);
  }
  if (!brief.plan) {
    throw new Error("Brief has no generated plan — run /generate first");
  }

  // ── 2. Load requester coin balance
  const user = await prisma.user.findUnique({
    where: { id: requesterId },
    select: { id: true, role: true },
  });
  if (!user) throw new Error("User not found");

  const plan = brief.plan;
  const rewardPolicy = plan.rewardPolicy as any;
  const audienceCriteria = plan.audienceCriteria as any;
  const screeningData = plan.screening as any;
  const quotaData = plan.quota as any;
  const surveyData = plan.survey as any;
  const qualityPolicy = plan.qualityPolicy as any;

  // ── 3. Compute financials
  const sampleSize: number = quotaData?.total ?? brief.targetSampleSize ?? 100;
  const rewardPerParticipant: number = rewardPolicy?.rewardPerParticipant ?? 20;
  const totalRewardCents = Math.ceil(sampleSize * rewardPerParticipant);
  const platformFeeCents = Math.ceil(totalRewardCents * PLATFORM_FEE_RATE);
  const totalEscrowCents = totalRewardCents + platformFeeCents;

  // Check balance (skip for ADMIN)
  if (user.role !== "ADMIN") {
    const balance: number = (user as any).coinBalance ?? 0;
    if (balance < totalEscrowCents) {
      throw new Error(
        `Insufficient coin balance. Required: ${totalEscrowCents} coins (reward ${totalRewardCents} + fee ${platformFeeCents}), available: ${balance}.`,
      );
    }
  }

  // ── 4. Estimate real audience size
  const eligibleCount = await estimateAudienceSize({
    countries: audienceCriteria?.countries,
    regions: audienceCriteria?.regions,
    industries: audienceCriteria?.industries,
    employmentStatuses: audienceCriteria?.employmentStatuses,
    minimumTrustScore: audienceCriteria?.minimumTrustScore,
    minimumQualityScore: audienceCriteria?.minimumQualityScore,
  }).catch(() => 0);

  // ── 5. Ensure global remote location exists
  await prisma.location.upsert({
    where: { id: GLOBAL_LOCATION_ID },
    create: {
      id: GLOBAL_LOCATION_ID,
      name: "Remote / Online",
      city: "Global",
      country: "Global",
      countryCode: "GL",
      latitude: 0,
      longitude: 0,
      timezone: "UTC",
    },
    update: {},
  });

  // ── 6. Build survey title / description
  const missionTitle = brief.title ?? surveyData?.title ?? "Research Survey";
  const missionDescription =
    brief.objective?.slice(0, 1000) ??
    surveyData?.title ??
    "Survey generated by AI Research Copilot";

  // ── 7. Mission expiry — default 30 days
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  // ── 8. Screening questions — adapt from plan schema to mission schema
  const screeningEnabled: boolean = screeningData?.enabled ?? false;
  const screeningQuestions =
    screeningEnabled && Array.isArray(screeningData?.questions)
      ? screeningData.questions.map((q: any, idx: number) => ({
          id: q.tempId ?? `sq-${idx + 1}`,
          question: q.question,
          type: q.type,
          options: q.options ?? [],
          required: q.required ?? true,
          order: q.order ?? idx + 1,
          eligibleAnswers: q.isEliminationQuestion
            ? (q.options ?? []).filter((o: string) => o !== q.eliminationAnswer)
            : [],
        }))
      : null;

  // ── 9. Quotas — adapt from plan quota schema
  const quotas =
    Array.isArray(quotaData?.quotas) && quotaData.quotas.length > 0 ? quotaData.quotas : null;

  // ── 10. Atomic transaction: create mission + escrow
  const missionId = crypto.randomUUID();
  const idempotencyKey = `copilot-escrow-${briefId}`;

  let surveyQuestionsCreated = 0;

  await prisma.$transaction(async (tx) => {
    // Create mission
    await tx.mission.create({
      data: {
        id: missionId,
        title: missionTitle,
        description: missionDescription,
        category: "SURVEY",
        status: "OPEN",
        urgency: "NORMAL",
        budgetCents: totalRewardCents,
        currency: "VND",
        locationId: GLOBAL_LOCATION_ID,
        latitude: 0,
        longitude: 0,
        radiusMeters: 0,
        requesterId,
        requiredTags: [],
        expiresAt,
        // Audience targeting
        rewardPerValidSubmissionCents: rewardPerParticipant,
        rewardBudgetCents: totalRewardCents,
        remainingBudgetCents: totalRewardCents,
        logVisibility: "PRIVATE",
        selectionMode: audienceCriteria?.selectionMode ?? "AUTO",
        disputeMode: "DISABLED",
        maxParticipants: sampleSize,
        // Screening
        screeningEnabled,
        screeningQuestions: (screeningQuestions as any) ?? undefined,
        // Quota
        quotas: (quotas as any) ?? undefined,
        // Trust targeting from audience criteria
        minimumTrustScore: audienceCriteria?.minimumTrustScore ?? null,
        minimumQualityScore: audienceCriteria?.minimumQualityScore ?? null,
        minimumCompletedMissions: audienceCriteria?.minimumCompletedMissions ?? null,
        verifiedOnly: audienceCriteria?.verifiedOnly ?? false,
        // Copilot traceability
        sourceBriefId: briefId,
      },
    });

    // Escrow coins: MISSION_REWARD_LOCK
    await recordCoinMovement(tx as any, {
      userId: requesterId,
      missionId,
      type: "MISSION_REWARD_LOCK",
      amountCents: totalEscrowCents,
      description: `Escrow for copilot mission "${missionTitle}" (${sampleSize} participants × ${rewardPerParticipant} coins + ${platformFeeCents} platform fee)`,
      idempotencyKey,
    });

    // Deduct balance (skip for ADMIN)
    if (user.role !== "ADMIN" && (user as any).coinBalance != null) {
      await (tx as any).user.update({
        where: { id: requesterId },
        data: { coinBalance: { decrement: totalEscrowCents } },
      });
    }

    // Create survey questions from plan
    if (Array.isArray(surveyData?.questions)) {
      for (const q of surveyData.questions) {
        await tx.surveyQuestion.create({
          data: {
            missionId,
            order: q.order ?? 1,
            type: q.type,
            question: q.question,
            description: q.description ?? null,
            required: q.required ?? true,
            options: q.options ?? null,
            validation: q.validation ?? null,
            condition: q.condition ?? null,
          },
        });
        surveyQuestionsCreated++;
      }
    }

    // Store quality policy on the plan for reference
    await tx.researchPlan.update({
      where: { briefId },
      data: {
        estimatedEligibleCount: eligibleCount,
        estimatedCost: totalEscrowCents,
        updatedAt: new Date(),
      },
    });

    // Mark brief PUBLISHED
    await tx.researchBrief.update({
      where: { id: briefId },
      data: { status: "PUBLISHED", updatedAt: new Date() },
    });
  });

  return {
    missionId,
    briefId,
    status: "PUBLISHED",
    escrowedCents: totalEscrowCents,
    platformFeeCents,
    surveyQuestionsCreated,
    eligibleCount,
  };
}

/**
 * Get mission created from a copilot brief
 */
export async function getMissionFromBrief(briefId: string, requesterId: string) {
  const brief = await prisma.researchBrief.findUnique({
    where: { id: briefId },
    select: { requesterId: true, status: true },
  });
  if (!brief || brief.requesterId !== requesterId) throw new Error("Not found or forbidden");

  const mission = await prisma.mission.findFirst({
    where: { sourceBriefId: briefId },
    include: {
      surveyQuestions: { orderBy: { order: "asc" } },
      coinLedgers: { where: { type: "MISSION_REWARD_LOCK" }, take: 1 },
    },
  });

  return mission;
}
